### ISSUE TITLE
I want to run tpcc benchmark on two machine using hstore, but I failed

### ISSUE THREAD

**Issue by psnbbgy** [apavlo/h-store#194]
I want to run the benchmark on two machine named "node233" and "node234". I can run the benchmark on them alone, but when I want to run the benchmark on the cluster consisting of node233 and node234 it failed, I got the information : 

[java] 17:05:32,777 INFO  - ------------------------- BENCHMARK INITIALIZE :: TPCC -------------------------
     [java] 17:05:32,849 INFO  - Starting HStoreSite H00 on node233
     [java] 17:05:32,854 INFO  - Starting HStoreSite H01 on node234
     [java] 17:05:32,857 INFO  - Waiting for 2 HStoreSites with 2 partitions to finish initialization
     [java] 17:05:37,857 ERROR - Failed to poll 'site-00-node233' [exitValue=255]
     [java] 17:05:37,857 FATAL - Process 'site-00-node233' failed. Halting benchmark!
     [java] 17:05:39,361 FATAL - Failed to complete benchmark
     [java] java.lang.RuntimeException: Failed to start all HStoreSites. Halting benchmark
     [java] 	at edu.brown.api.BenchmarkController.startSites(BenchmarkController.java:633)
     [java] 	at edu.brown.api.BenchmarkController.setupBenchmark(BenchmarkController.java:504)
     [java] 	at edu.brown.api.BenchmarkController.main(BenchmarkController.java:2230)

BUILD FAILED
/home4/liguiyang/memorydb/h-store-release-2014-05/build.xml:2558: The following error occurred while executing this line:
/home4/liguiyang/memorydb/h-store-release-2014-05/build.xml:1716: Java returned: 1

and when I set the node234 as 0 partition I got the information: 

[java] 16:45:39,756 INFO  - ------------------------- BENCHMARK INITIALIZE :: TPCC -------------------------
     [java] 16:45:39,811 INFO  - Starting HStoreSite H00 on node234
     [java] 16:45:39,817 INFO  - Starting HStoreSite H01 on node233
     [java] 16:45:39,819 INFO  - Waiting for 2 HStoreSites with 2 partitions to finish initialization
     [java] 16:45:44,819 ERROR - Failed to poll 'site-01-node233' [exitValue=0]
     [java] 16:45:44,819 FATAL - Process 'site-01-node233' failed. Halting benchmark!
     [java] 16:45:46,321 FATAL - Failed to complete benchmark
     [java] java.lang.RuntimeException: Failed to start all HStoreSites. Halting benchmark
     [java] 	at edu.brown.api.BenchmarkController.startSites(BenchmarkController.java:633)
     [java] 	at edu.brown.api.BenchmarkController.setupBenchmark(BenchmarkController.java:504)
     [java] 	at edu.brown.api.BenchmarkController.main(BenchmarkController.java:2230)

BUILD FAILED
/home4/liguiyang/memorydb/h-store-release-2014-05/build.xml:2558: The following error occurred while executing this line:
/home4/liguiyang/memorydb/h-store-release-2014-05/build.xml:1716: Java returned: 1

I can use ssh instruction to login between 233 and 234, so what is the problem?

**Comment by apavlo** [comment]
What is in your server logs?

http://hstore.cs.brown.edu/documentation/faq/#q8

If you switch the host names to be "localhost", does it work?

**Comment by psnbbgy** [comment]
you mean run it locally? If I run it locally, it works.and the server logs:

hstore-site:
18:06:22,234 [main] (HStore.java:227) WARN  -
?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?....?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?
?.H-Store is executing with JVM asserts enabled. This will degrade runtime performance. ?
?.You can disable them by setting the config option 'site.jvm_asserts' to FALSE         ?
?.See the online documentation for more information:                                    ?
?.   http://hstore.cs.brown.edu/documentation/deployment/client-configuration           ?
?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?....?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?..?
18:06:25,871 [H00-main] (HStoreCoordinator.java:559) FATAL - Site #0 failed to connect to remote sites
18:06:25,872 [H00-main] (HStoreSite.java:573) FATAL - Thread H00-main had a fatal error: null
java.lang.RuntimeException
        at edu.brown.hstore.HStoreCoordinator.initConnections(HStoreCoordinator.java:561)
        at edu.brown.hstore.HStoreCoordinator.start(HStoreCoordinator.java:390)
        at edu.brown.hstore.HStoreSite.init(HStoreSite.java:706)
        at edu.brown.hstore.HStoreSite.run(HStoreSite.java:1501)
        at edu.brown.hstore.HStore.main(HStore.java:266)
18:06:25,878 [H00-main] (HStoreCoordinator.java:1549) WARN  - Shutting down cluster with RuntimeException
java.lang.RuntimeException
        at edu.brown.hstore.HStoreCoordinator.initConnections(HStoreCoordinator.java:561)
        at edu.brown.hstore.HStoreCoordinator.start(HStoreCoordinator.java:390)
        at edu.brown.hstore.HStoreSite.init(HStoreSite.java:706)
        at edu.brown.hstore.HStoreSite.run(HStoreSite.java:1501)
        at edu.brown.hstore.HStore.main(HStore.java:266)
18:06:25,882 [H00-main] (HStoreCoordinator.java:1512) ERROR - Trying to send ShutdownPrepareRequest to H01 before the connection was established
18:06:25,883 [H00-main] (HStoreCoordinator.java:1530) INFO  - Waiting for 1 sites to finish shutting down
18:06:35,883 [H00-main] (HStoreCoordinator.java:1533) WARN  - Failed to recieve all shutdown responses
18:06:40,884 [H00-main] (HStoreCoordinator.java:1563) INFO  - Sending final shutdown message to 1 remote sites
java.lang.NullPointerException
        at edu.brown.hstore.HStoreCoordinator.shutdownClusterBlocking(HStoreCoordinator.java:1580)
        at edu.brown.hstore.HStoreSite$3.update(HStoreSite.java:576)
        at edu.brown.hstore.HStoreSite$3.update(HStoreSite.java:566)
        at edu.brown.utils.EventObserver$InnerObserver.update(EventObserver.java:43)
        at java.util.Observable.notifyObservers(Observable.java:159)
18:06:40,887 [H00-main] (HStoreCoordinator.java:1593) INFO  - Shutting down [site=0 / exitCode=1]
        at edu.brown.utils.EventObservable.notifyObservers(EventObservable.java:85)
18:06:40,887 [H00-main] (HStoreCoordinator.java:1596) FATAL - A fatal error caused this shutdown
        at edu.brown.utils.EventObservableExceptionHandler.uncaughtException(EventObservableExceptionHandler.java:40)
java.lang.RuntimeException
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
        at edu.brown.hstore.HStoreCoordinator.initConnections(HStoreCoordinator.java:561)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1986)
        at edu.brown.hstore.HStoreCoordinator.start(HStoreCoordinator.java:390)
        at edu.brown.hstore.HStoreSite.init(HStoreSite.java:706)
        at edu.brown.hstore.HStoreSite.run(HStoreSite.java:1501)
        at edu.brown.hstore.HStore.main(HStore.java:266)

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "H00-main"
Java Result: 1
BUILD SUCCESSFUL
Total time: 19 seconds

it seems that it cannot connect the node233, but I can use ssh to log it without passwd, is there any other reason can get this result?
