### ISSUE TITLE
Failed to poll 'site-01-localhost' on running TPCC benchmark

### ISSUE THREAD

**Issue by saurabhska** [apavlo/h-store#204]
Hi,

I am trying to run TPCC benchmark on h-store, but its unfortunately getting failed. 
Please find the below logs from my run and appreciate if you can help me debug it. (seems like a configuration issue to me, but I am unable to find where am I going wrong)

$ ant hstore-prepare -Dproject=$BENCHMARK -Dhosts=./cluster.txt
Buildfile: /home/h-store/build.xml

hstore-prepare:

benchmark:
     [java] 16:33:53,894 INFO  - Compiling TPCC benchmark project jar
     [java] 16:33:57,701 INFO  - Compilation Complete. Exiting [/home/h-store/./tpcc.jar]

hstore-jar:

catalog-fix:
     [copy] Copying 1 file to /home/h-store/obj/backup
    [unjar] Expanding: /home/h-store/tpcc.jar into /home/h-store/obj/fixcatalog
     [java] 16:33:59,275 [main] (FixCatalog.java:130) INFO  - Updated host information in catalog with 1 host and 2 partitions
      [jar] Building jar: /home/h-store/tpcc.jar
   [delete] Deleting directory /home/h-store/obj/fixcatalog

BUILD SUCCESSFUL
Total time: 7 seconds
$ cat ./cluster.txt 
host0.cs.brown.edu:0:0
host0.cs.brown.edu:0:1
$ ant catalog-info -Dproject=tpcc
Buildfile: /home/h-store/build.xml

catalog-info:
     [java] Catalog File:    /home/h-store/tpcc.jar
     [java] # of Hosts:      1
     [java] # of Sites:      1
     [java] # of Partitions: 2
     [java] ---------------------------------------------------------------
     [java] Cluster Information:
     [java] [00] HOST host0.cs.brown.edu
     [java]      └ SITE H00: [0, 1]     
     [java] 

BUILD SUCCESSFUL
Total time: 1 second
$ ant hstore-benchmark -Dproject=tpcc
Buildfile: /home/h-store/build.xml

hstore-benchmark:

benchmark:
     [java] 16:34:29,435 INFO  - ------------------------- BENCHMARK INITIALIZE :: TPCC -------------------------
     [java] 16:34:29,485 INFO  - Starting HStoreSite H00 on host0.cs.brown.edu
     [java] 16:34:29,494 INFO  - Waiting for 1 HStoreSite with 2 partitions to finish initialization
     [java] 16:34:34,495 ERROR - Failed to poll 'site-00-host0.cs.brown.edu' [exitValue=255]
     [java] 16:34:34,495 FATAL - Process 'site-00-host0.cs.brown.edu' failed. Halting benchmark!
     [java] 16:34:35,997 FATAL - Failed to complete benchmark
     [java] java.lang.RuntimeException: Failed to start all HStoreSites. Halting benchmark
     [java] 	at edu.brown.api.BenchmarkController.startSites(BenchmarkController.java:634)
     [java] 	at edu.brown.api.BenchmarkController.setupBenchmark(BenchmarkController.java:505)
     [java] 	at edu.brown.api.BenchmarkController.main(BenchmarkController.java:2238)

BUILD FAILED
/home/h-store/build.xml:2565: The following error occurred while executing this line:
/home/h-store/build.xml:1722: Java returned: 1

Total time: 9 seconds

**Comment by mikelj** [comment]
Unless you're running on the 'host0.cs.brown.edu' machine, this won't work. Try 'localhost' for the cluster machines.

**Comment by saurabhska** [comment]
Hi,

I am still getting the below error. Can you please help me understand what exactly should I try?

$ant hstore-prepare -Dproject=$BENCHMARK -Dhosts=./cluster.txt
Buildfile: /home/saurabhska/cs550Project/h-store/build.xml

hstore-prepare:

benchmark:
     [java] 23:37:42,285 INFO  - Compiling TPCC benchmark project jar
     [java] 23:37:46,244 INFO  - Compilation Complete. Exiting [/home/saurabhska/cs550Project/h-store/./tpcc.jar]

hstore-jar:

catalog-fix:
     [copy] Copying 1 file to /home/saurabhska/cs550Project/h-store/obj/backup
    [unjar] Expanding: /home/saurabhska/cs550Project/h-store/tpcc.jar into /home/saurabhska/cs550Project/h-store/obj/fixcatalog
     [java] 23:37:47,783 [main] (FixCatalog.java:130) INFO  - Updated host information in catalog with 1 host and 2 partitions
      [jar] Building jar: /home/saurabhska/cs550Project/h-store/tpcc.jar
   [delete] Deleting directory /home/saurabhska/cs550Project/h-store/obj/fixcatalog

BUILD SUCCESSFUL
Total time: 7 seconds
saurabhska@saurabhska-Lenovo-Z40-70:~/cs550Project/h-store$ ant catalog-info -Dproject=tpcc
Buildfile: /home/saurabhska/cs550Project/h-store/build.xml

catalog-info:
     [java] Catalog File:    /home/saurabhska/cs550Project/h-store/tpcc.jar
     [java] # of Hosts:      1
     [java] # of Sites:      1
     [java] # of Partitions: 2
     [java] ---------------------------------------------------------------
     [java] Cluster Information:
     [java] [00] HOST localhost    
     [java]      └ SITE H00: [0, 1]
     [java] 

BUILD SUCCESSFUL
Total time: 1 second
saurabhska@saurabhska-Lenovo-Z40-70:~/cs550Project/h-store$ ant hstore-benchmark -Dproject=tpcc
Buildfile: /home/saurabhska/cs550Project/h-store/build.xml

hstore-benchmark:

benchmark:
     [java] 23:38:39,654 INFO  - ------------------------- BENCHMARK INITIALIZE :: TPCC -------------------------
     [java] 23:38:39,710 INFO  - Starting HStoreSite H00 on localhost
     [java] 23:38:39,717 INFO  - Waiting for 1 HStoreSite with 2 partitions to finish initialization
     [java] 23:38:44,718 ERROR - Failed to poll 'site-00-localhost' [exitValue=255]
     [java] 23:38:44,718 FATAL - Process 'site-00-localhost' failed. Halting benchmark!
     [java] 23:38:46,220 FATAL - Failed to complete benchmark
     [java] java.lang.RuntimeException: Failed to start all HStoreSites. Halting benchmark
     [java] 	at edu.brown.api.BenchmarkController.startSites(BenchmarkController.java:634)
     [java] 	at edu.brown.api.BenchmarkController.setupBenchmark(BenchmarkController.java:505)
     [java] 	at edu.brown.api.BenchmarkController.main(BenchmarkController.java:2238)

BUILD FAILED
/home/saurabhska/cs550Project/h-store/build.xml:2565: The following error occurred while executing this line:
/home/saurabhska/cs550Project/h-store/build.xml:1722: Java returned: 1

Total time: 9 seconds

**Comment by apavlo** [comment]
What is in your site log files?

http://hstore.cs.brown.edu/documentation/faq/#q8

**Comment by saurabhska** [comment]
Hi,

I apologize for the delayed response, but the log file is empty with only the timestamp i.e 
# 2015-11-19T15:47:40.385.0

**Comment by apavlo** [comment]
Did you setup passwordless SSH properly?

**Comment by saurabhska** [comment]
Its my bad, since I was using it on a single machine, I didn't try to configure SSH. After doing SSH configuration it works fine. Thanks for your help!
One quick question -
Is there a way of specifying different workloads (amount of reads/writes) for  TPCC benchmark on hstore?

**Comment by apavlo** [comment]
There is an undocumented features where you can control the workload mixture of txns:

http://hstore.cs.brown.edu/documentation/configuration/properties-file/client/#weights

So you can pass in from the commandline the distributed of how transactions are executed. For example, in TPC-C, if you wanted to just executed NewOrder 50% of the time and Payment 50% of the time, you would would set the parameter like this:

```
-Dclient.weights="NewOrder:50,PaymentByCustomerId:50,*:0"
```

The value of the parameter is a semi-colon separated list of entries. Each entry in the list is a pair `<TxnName>:<Weight>` where TxnName is the name of the txn (it's java class) and the weight is a value 0-100 of the percentage of the workload that should be comprised of that txn. You can use `*` to mean all other transactions. The weights have to add up to 100.

**Comment by saurabhska** [comment]
Thanks for this comment.

I am trying to make TPCC read intensive and test it on HSTORE for performance. The two methods that you shared in the example works perfect, but when I try to run it for different methods it fails. I believe its because the method names are case sensitive like (NewOrder and PaymentByCustomerId). 

Can you please help me with it i.e how to make the TPCC workload read-intensive?

**Comment by apavlo** [comment]
I don't know what you mean by "methods"? Do you mean stored procedures?

There are only two read-only stored procedures in TPC-C: `ostatByCustomer*` and `slev`.

**Comment by saurabhska** [comment]
Basically I need to test HSTORE for its performance on read-intensive and write-intensive workloads. The default TPCC workload is write intensive, so I am wondering how can I make it read intensive?

Like the example you gave - 
-Dclient.weights="NewOrder:50,PaymentByCustomerId:50,*:0"

with syntax - <TxnName>:<Weight> ,

I am wondering which other TxnNames can I use to make a read-intensive test workload.

**Comment by apavlo** [comment]
I just told you. Read my last comment.
