### ISSUE TITLE
Failed to use hstore command line tool 

### ISSUE THREAD

**Issue by Meditator-hkx** [apavlo/h-store#214]
The fault information is listed as below:

```
kaixin@kaixin-VirtualBox:~/h-store$ ./hstore tpcc
17:17:39,116 ERROR - Failed to get connection to localhost:21212
Exception in thread "main" java.lang.RuntimeException: Failed to connect to HStoreSite at localhost:21212
	at edu.brown.terminal.HStoreTerminal.getClientConnection(HStoreTerminal.java:278)
	at edu.brown.terminal.HStoreTerminal.run(HStoreTerminal.java:116)
	at edu.brown.terminal.HStoreTerminal.main(HStoreTerminal.java:491)
kaixin@kaixin-VirtualBox:~/h-store$ ./hstore tpcc
17:18:00,373 ERROR - Failed to get connection to localhost:21212
Exception in thread "main" java.lang.RuntimeException: Failed to connect to HStoreSite at localhost:21212
	at edu.brown.terminal.HStoreTerminal.getClientConnection(HStoreTerminal.java:278)
	at edu.brown.terminal.HStoreTerminal.run(HStoreTerminal.java:116)
	at edu.brown.terminal.HStoreTerminal.main(HStoreTerminal.java:491)
```

However, that tpcc benchmark has been successful already when using
> ant hstore-prepare -Dproject=tpcc
and
> ant hstore-benchmark -Dproject=tpcc

The catalog info is given as below:
```
kaixin@kaixin-VirtualBox:~/h-store$ ant catalog-info -Dproject=tpcc
Buildfile: /home/kaixin/h-store/build.xml

catalog-info:
     [java] Catalog File:    /home/kaixin/h-store/tpcc.jar
     [java] # of Hosts:      1
     [java] # of Sites:      2
     [java] # of Partitions: 2
     [java] ----------------------------------------------
     [java] Cluster Information:
     [java] [00] HOST localhost 
     [java]      ├ SITE H00: [0]
     [java]      └ SITE H01: [1]
     [java] 

BUILD SUCCESSFUL
Total time: 2 seconds
```

I just don't understand why it couldn't connect the localhost since no password ssh has been set properly.
Hope you can give me some help. If more information is needed, please tell me.

**Comment by apavlo** [comment]
Is the server actually running? Start up the system in one terminal:

```$ ant hstore-benchmark -Dproject=tpcc -Dnoshutdown=true -Dnoexecute=true```

Then connect to it with another terminal:

```./hstore tpcc```

**Comment by Meditator-hkx** [comment]
Oh, my fault. Your answer perfectly solved my problem. I'll remember to keep  the server running later.
